### ISSUE TITLE
推荐你几款高效的办公软件玩一下

### ISSUE THREAD

**Issue by leprode** [cxm1011/myselfStudy#2]
1. snipaste
2. chrome里面的插件cVim，具体github下载链接我忘了，今天刚接触，玩到现在
3. everything
4. vim
...

i will build a new project to save this good idea& good tools, please follow...
:)

**Comment by cxm1011** [comment]
so happy

**Comment by cxm1011** [comment]
> 1. snipaste
> 2. chrome里面的插件cVim，具体github下载链接我忘了，今天刚接触，玩到现在
> 3. everything
> 4. vim
>    ...
> 
> i will build a new project to save this good idea& good tools, please follow...
> :)

敬请期待

**Comment by leprode** [comment]
如果你认为半夜1点半失眠叫happy的话，那我无话可说

**Comment by leprode** [comment]
最近有点迷键盘党，昨天刚用了cVim，半夜还买了手托和指尖保护套，打算一年后拔掉鼠标了

**Comment by leprode** [comment]
啥叫敬请期待，这是我该说的话

试试snipaste，昨天刚推荐给心动和伟伦，试过都说好用

f1是截图，f3是截图浮窗，我只用这两个快捷键

**Comment by leprode** [comment]
换个头像吧，还用默认的，真丑

**Comment by cxm1011** [comment]
> 如果你认为半夜1点半失眠叫happy的话，那我无话可说

还失眠  我都迷茫了

**Comment by leprode** [comment]
迷茫个啥，好好上班，怎么迷茫了说说看，让我点醒你

**Comment by leprode** [comment]
妈的，github没有消息提醒功能，真费劲，今天搜一个出来装起来，这样就不会漏信息了

**Comment by cxm1011** [comment]
> 迷茫个啥，好好上班，怎么迷茫了说说看，让我点醒你

你怎么有空了

**Comment by leprode** [comment]
我天天有空，每天都有8w秒

**Comment by leprode** [comment]
对敏博，每天浪费50秒我是愿意的

**Comment by cxm1011** [comment]
github会不会被你玩奔溃

**Comment by leprode** [comment]
那说明是他的架构问题

**Comment by leprode** [comment]
又不聊天了，我们真的要这么尬聊么，都枉费我时不时切过来瞅一眼

**Comment by leprode** [comment]
完蛋了，坑爹了，自己坑自己了，提commit的思路没想清楚，按文件拆还不够，得具体到每一行代码了，坑爹啊。。。。

**Comment by leprode** [comment]
你也不说具体问题，我都不知道该怎么帮你了

**Comment by leprode** [comment]
呼，解决了，花了10分钟，还好还好

**Comment by leprode** [comment]
我今天归档，se还没开始检视我代码，我3天才码了800行小代码，还得拆3个pr，妈的，今天得几点才能下班呢·

**Comment by leprode** [comment]
我还没上环境验证过，只对齐了验证思路，因为我这个属于对环境破坏性比较大的操作，得人少的时候验证，白天都不太敢动环境。。。

**Comment by leprode** [comment]
我前半年被压榨的太狠了，一个月加班超过120个小时，现在每天睡眠时间很短，张婷说我这么下去，要活不过50岁了，我现在每天10点准时下班

**Comment by leprode** [comment]
敏博，你看看你现在最痛苦的点是啥，总结一下，我帮你分析分析
